package:
  name: tetragono
  version: 0.2.1

source:
  url: https://github.com/hzhangxyz/TAT/archive/refs/heads/dev.zip

build:
  script: |
     cp setup/tetragono.py setup.py

requirements:
  run:
    - lazy_graph
    - PyTAT
    - numpy
    - CLAPACK
