package:
  name: PyTAT
  version: 0.2.1

source:
  url: https://github.com/hzhangxyz/TAT/archive/refs/heads/dev.zip

build:
  script: |
     git clone https://github.com/pybind/pybind11.git
     cd PyTAT
     bash ./generator.sh
     cd ..
     cp setup/PyTAT.py setup.py

requirements:
  run:
    - numpy
    - CLAPACK
